#!/bin/bash

CURDIR=`pwd`
PROJECT_NAME=SailfishWidgets
BUILD_DIR=build
TARGET_DIR=target
DEPLOY_DIR=$TARGET_DIR/$PROJECT_NAME
QML_DIR=SailfishWidgets
RELEASE_DIR=release
DOC_DIR=Documentation

VERSION=1_3
ARMV=armv
i486=i486

rm -fr $TARGET_DIR

#copy qml files
mkdir -p $DEPLOY_DIR
mkdir -p $DEPLOY_DIR/$ARMV
mkdir -p $DEPLOY_DIR/$i486
mkdir -p $RELEASE_DIR
cp -r $QML_DIR $DEPLOY_DIR/$ARMV
cp -r $QML_DIR $DEPLOY_DIR/$i486

TARGET_ARMV=$DEPLOY_DIR/$ARMV/$QML_DIR
TARGET_i486=$DEPLOY_DIR/$i486/$QML_DIR

#copy built plugins
cp $BUILD_DIR/applicationsettings/$ARMV/*.so $TARGET_ARMV/Settings/
cp $BUILD_DIR/applicationsettings/$i486/*.so $TARGET_i486/Settings/
cp $BUILD_DIR/filemanagement/$ARMV/*.so $TARGET_ARMV/FileManagement/
cp $BUILD_DIR/filemanagement/$i486/*.so $TARGET_i486/FileManagement/

#documentation
qdoc3 *.qdocconf
cp -r $DOC_DIR $DEPLOY_DIR

#release builds

cd $TARGET_DIR
tar -cvjf $PROJECT_NAME\_$VERSION\.tar.bz2 *
cd $CURDIR
cp $TARGET_DIR/*bz2 $RELEASE_DIR/
